[2025-08-13T11:29:19.592+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-13T11:29:19.612+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T15:00:00+00:00 [queued]>
[2025-08-13T11:29:19.619+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T15:00:00+00:00 [queued]>
[2025-08-13T11:29:19.619+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-08-13T11:29:19.627+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): spark_hourly_change> on 2025-08-12 15:00:00+00:00
[2025-08-13T11:29:19.631+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'crypto_hourly_pipeline', 'spark_hourly_change', 'scheduled__2025-08-12T15:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/crypto_pipeline.py', '--cfg-path', '/tmp/tmp1295f33p']
[2025-08-13T11:29:19.634+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask spark_hourly_change
[2025-08-13T11:29:19.634+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=167) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-13T11:29:19.635+0000] {standard_task_runner.py:63} INFO - Started process 168 to run task
[2025-08-13T11:29:19.673+0000] {task_command.py:426} INFO - Running <TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T15:00:00+00:00 [running]> on host 6533932e16b6
[2025-08-13T11:29:19.737+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_hourly_pipeline' AIRFLOW_CTX_TASK_ID='spark_hourly_change' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T15:00:00+00:00'
[2025-08-13T11:29:19.737+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-13T11:29:19.758+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-13T11:29:19.758+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/project && python spark_hourly_change.py']
[2025-08-13T11:29:19.763+0000] {subprocess.py:86} INFO - Output:
[2025-08-13T11:29:21.198+0000] {subprocess.py:93} INFO - 2025-08-13 11:29:21,198 - INFO - Starting hourly change calculation...
[2025-08-13T11:29:21.214+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-08-13T11:29:21.215+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-17-openjdk-amd64/bin/java: No such file or directory
[2025-08-13T11:29:21.215+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2025-08-13T11:29:21.306+0000] {subprocess.py:93} INFO - 2025-08-13 11:29:21,306 - ERROR - Hourly change calculation failed: Java gateway process exited before sending its port number
[2025-08-13T11:29:21.307+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-13T11:29:21.307+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 176, in <module>
[2025-08-13T11:29:21.307+0000] {subprocess.py:93} INFO -     main()
[2025-08-13T11:29:21.307+0000] {subprocess.py:93} INFO -     ^^^^^^
[2025-08-13T11:29:21.307+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 155, in main
[2025-08-13T11:29:21.307+0000] {subprocess.py:93} INFO -     spark = create_spark_session()
[2025-08-13T11:29:21.307+0000] {subprocess.py:93} INFO -             ^^^^^^^^^^^^^^^^^^^^^^
[2025-08-13T11:29:21.308+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 48, in create_spark_session
[2025-08-13T11:29:21.308+0000] {subprocess.py:93} INFO -     .getOrCreate()
[2025-08-13T11:29:21.308+0000] {subprocess.py:93} INFO -      ^^^^^^^^^^^^^
[2025-08-13T11:29:21.308+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 477, in getOrCreate
[2025-08-13T11:29:21.308+0000] {subprocess.py:93} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-08-13T11:29:21.308+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-13T11:29:21.308+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 512, in getOrCreate
[2025-08-13T11:29:21.308+0000] {subprocess.py:93} INFO -     SparkContext(conf=conf or SparkConf())
[2025-08-13T11:29:21.309+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 198, in __init__
[2025-08-13T11:29:21.309+0000] {subprocess.py:93} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-08-13T11:29:21.309+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 432, in _ensure_initialized
[2025-08-13T11:29:21.309+0000] {subprocess.py:93} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-08-13T11:29:21.309+0000] {subprocess.py:93} INFO -                                        ^^^^^^^^^^^^^^^^^^^^
[2025-08-13T11:29:21.309+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 106, in launch_gateway
[2025-08-13T11:29:21.309+0000] {subprocess.py:93} INFO -     raise RuntimeError("Java gateway process exited before sending its port number")
[2025-08-13T11:29:21.309+0000] {subprocess.py:93} INFO - RuntimeError: Java gateway process exited before sending its port number
[2025-08-13T11:29:21.391+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-13T11:29:21.391+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-13T11:29:21.403+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-13T11:29:21.406+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=crypto_hourly_pipeline, task_id=spark_hourly_change, run_id=scheduled__2025-08-12T15:00:00+00:00, execution_date=20250812T150000, start_date=20250813T112919, end_date=20250813T112921
[2025-08-13T11:29:21.416+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task spark_hourly_change (Bash command failed. The command returned a non-zero exit code 1.; 168)
[2025-08-13T11:29:21.456+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-13T11:29:21.468+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-13T11:29:21.469+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
